# Generated by Django 6.1.1 on 2026-09-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For example: test or production', max_length=50, unique=True)),
                ('access_token', models.TextField()),
                ('phone_number_id', models.CharField(max_length=50)),
                ('verify_token', models.CharField(max_length=100)),
                ('app_secret', models.CharField(blank=True, max_length=100)),
                ('api_version', models.CharField(default='v21.0', max_length=10)),
                ('default_template', models.CharField(blank=True, default='invoice_simple', max_length=100)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=False, help_text='Only one connection can be active at a time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ['-received_at']},
        ),
        migrations.AlterModelOptions(
            name='whatsappmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
