# Generated by Django 6.1.1 on 2026-09-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappconfig_alter_webhookevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='busy_api_key',
            field=models.CharField(blank=True, help_text='Secret that BUSY sends as ?key=... when calling /api/busy/send/', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='default_country_code',
            field=models.CharField(default='91', help_text='Added to 10-digit mobile numbers, for example 91 for India', max_length=5),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='waba_id',
            field=models.CharField(blank=True, help_text='Meta: WhatsApp > API Setup. Used to look up template status', max_length=50, verbose_name='WhatsApp Business Account ID'),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='api_version',
            field=models.CharField(default='v25.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='default_template',
            field=models.CharField(blank=True, default='test_templates', max_length=100),
        ),
    ]
